Finance react app
ridabensalem/react-capstone- pull request #4
Opened 2023-03-23 14:26 UTC by ridabensalem

In this milestone of reacting capstone, we have added the following requirements : 

- Choosed  the finance API 
- Fetched the endpoints of companies, sectors, and profile
- create the redux logic for stock, companies, and companies details 
- When the user clicks a stock it displays a list of companies ]
- Implement a search bar to filter the list of companies 
- when the user clicks the backward icon the app returns to the previous page 
- show details of the companies 
- Added routes to switch  between pages 
- Added tests for the app 
- Styled the app following the guidelines of Behance 
- Deployed the app

2023-03-23 15:19 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @ridabensalem, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️

Wow, well done on this project. 
- [ ] Based on the project requirement, you are suppose to add a a vdoe instead you added a `gif`  file withoutany voice. The video should be a maximum length of 5mins and should include the following:  
     - The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
     - The video contains a demo of the project, highlighting all the project features.
     - You should also highlight some interesting piece of code or something you built that you are very proud of.

For recording the video you can use tools like [Loom](https://www.loom.com/) that let you share a private link to the recording, and configure a shot that shows your computer screen and your face at the same time in a small picture.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 15:19 UTC, bobb-Rob commented on src/testing/apitest.test.js
> +});
- [ ] I see that you wrote tests for Async Thunk API Functions. Well done. But you are expected to write **_UNIT_** tests for several components of the app and some pure functions in Redux code. Also, your App should have integration tests using React Testing Library

* Student can perform a mocking data fetching and Redux Store connection.

Kindly add more tests for your components, you can even add screenshots test.

**See project requirement below 👇🏾** 
![image](https://user-images.githubusercontent.com/84156714/227248982-8b783d21-d560-4431-ae16-81deb9701739.png)

2023-03-23 23:11 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @ridabensalem,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-22 12:46 UTC, ShadyShawkat approved these changes
## Hi @ridabensalem, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 08:23 UTC, merged